import './globals.css'
import type { Metadata } from 'next'
import { NextFont } from "next/dist/compiled/@next/font";
import { Poppins } from 'next/font/google'
import Navbar from './components/navbar';
import Footer from './components/footer';

export const poppins: NextFont = Poppins({
  weight: ['400', '600'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'C4U',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative overflow-x-hidden ${poppins.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
