import './globals.css'
import type { Metadata } from 'next'
import { NextFont } from "next/dist/compiled/@next/font";
import { Poppins } from 'next/font/google'

export const poppins: NextFont = Poppins({
  weight: ['400', '600'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'C4U',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
